### ISSUE TITLE
[Feature request] Auto-rendered samples

### ISSUE THREAD

**Issue by Xiaohuba** [Wallbreaker5th/fuzzy-cnoi-statement#4]
I want the following function:

```typst
current-sample-rawfile(prefix, id, ext)
```

which has the same effect as

```typst
#raw(read(prefix + cur_problem + "/" + cur_problem + str(id) + "." + ext), block: true)
```

or something similar.

It can make writing statements for problems with long name easier.

**Comment by Wallbreaker5th** [comment]
You can define a function for the problem with a long name in the source file, which doesn't require changing the template.

**Comment by Xiaohuba** [comment]
Ok and thanks.

**Comment by Xiaohuba** [comment]
Ok and thanks.
